{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.createSecretStore }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.config.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName | quote }}
            namespace: {{ .Values.externalSecrets.serviceAccountNamespace | quote }}
{{- end }}
