apiVersion: v1
kind: ConfigMap
metadata:
  name: blacktickets-config
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_SSL: {{ .Values.config.dbSsl | quote }}
  POSTER_BUCKET_NAME: {{ .Values.config.posterBucketName | quote }}
  POSTER_CDN_DOMAIN: {{ .Values.config.posterCdnDomain | quote }}
  EVENT_SERVICE_URL: {{ .Values.config.eventServiceUrl | quote }}
  BOOKING_SERVICE_URL: {{ .Values.config.bookingServiceUrl | quote }}
  BOOKING_NOTIFICATION_QUEUE_URL: {{ .Values.config.bookingNotificationQueueUrl | quote }}
