{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | quote }}
    kind: {{ .Values.externalSecrets.secretStoreKind | quote }}
  target:
    name: {{ .Values.secrets.name | quote }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.remoteSecretName | quote }}
{{- end }}
