{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.createClass }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
spec:
  controllerName: gateway.k8s.aws/alb
---
{{- end }}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: blacktickets
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
spec:
  defaultConfiguration:
    targetType: ip
---
apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: blacktickets
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
spec:
  scheme: {{ .Values.gateway.scheme | quote }}
  defaultTargetGroupConfiguration:
    name: blacktickets
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: blacktickets
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "blacktickets.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: blacktickets
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      {{- with .Values.gateway.hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
