apiVersion: v1
kind: Secret
metadata:
  name: blacktickets-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  placeholder: replace-with-external-secrets
{{- end }}
