{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace | quote }}
  labels:
    {{- include "blacktickets.serviceLabels" (dict "root" $ "name" $name) | nindent 4 }}
  {{- if or (and $.Values.config.awsAccountId $svc.serviceAccount.roleName) $svc.serviceAccount.annotations }}
  annotations:
    {{- if and $.Values.config.awsAccountId $svc.serviceAccount.roleName }}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ $.Values.config.awsAccountId }}:role/{{ $.Values.config.roleNamePrefix | default $.Values.namespace }}-{{ $svc.serviceAccount.roleName }}"
    {{- end }}
    {{- with $svc.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
